name: Compilation & tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  job_build_debug_nano_s:
    name: Build debug
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder:latest

    steps:
      - name: Clone
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build an altcoin
        run: |
          make DEBUG=1 CHAIN=ethereum_classic

      - name: Upload altcoin binary
        uses: actions/upload-artifact@v2
        with:
          name: ethereum-classic-app-debug
          path: bin

      - name: Build Ethereum
        run: |
          make clean
          make DEBUG=1

      - name: Upload app binary
        uses: actions/upload-artifact@v2
        with:
          name: ethereum-app-debug
          path: bin

  job_build_debug_nano_x:
    name: Build debug
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder:latest

    steps:
      - name: Clone
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build an altcoin Nano X
        run: |
          make clean
          make BOLOS_SDK=$NANOX_SDK DEBUG=1 CHAIN=ethereum_classic

      - name: Upload altcoin binary
        uses: actions/upload-artifact@v2
        with:
          name: ethereum-classic-app-debug-nano-x
          path: bin

      - name: Build Ethereum Nano X
        run: |
          make clean
          make BOLOS_SDK=$NANOX_SDK DEBUG=1

      - name: Upload app binary
        uses: actions/upload-artifact@v2
        with:
          name: ethereum-app-debug-nano-x
          path: bin
